[PHP]
date.timezone = UTC
memory_limit = 256M
upload_max_filesize = 2M
post_max_size = 3M
max_execution_time = 60

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
